# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

class MyApp:
    def __init__(self, master):
        self.master = master
        self.OUTPUT_PATH = Path(__file__).parent
        self.ASSETS_PATH = self.OUTPUT_PATH / Path(r"./assets/frame0")
        self.canvas = Canvas(
            self.master,
            bg="#FFFFFF",
            height=600,
            width=1240,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        self.canvas.place(x=0, y=0)
        
        self.image_image_1 = PhotoImage(file=self.relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(293.0, 425.0, image=self.image_image_1)

        self.button_image_1 = PhotoImage(file=self.relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_1.place(x=1021.0, y=513.0, width=169.0, height=46.40189743041992)

        self.canvas.create_text(794.0, 30.0, anchor="nw", text="OOP SPEC", fill="#000000", font=("Inter SemiBold", 48 * -1))

        self.entry_image_1 = PhotoImage(file=self.relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(754.5, 187.5, image=self.entry_image_1)
        self.entry_1 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            font=("Inter SemiBold", 18 * -1),
            highlightthickness=0
        )
        self.entry_1.place(x=618.0, y=166.0, width=273.0, height=41.0)

        self.entry_image_2 = PhotoImage(file=self.relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(1077.5, 187.5, image=self.entry_image_2)
        self.entry_2 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            font=("Inter SemiBold", 18 * -1),
            highlightthickness=0
        )
        self.entry_2.place(x=941.0, y=166.0, width=273.0, height=41.0)

        self.canvas.create_text(951.0, 125.0, anchor="nw", text="Password", fill="#000000", font=("Inter SemiBold", 20 * -1))

        self.canvas.create_text(629.0, 125.0, anchor="nw", text="Username", fill="#000000", font=("Inter SemiBold", 20 * -1))

        self.entry_image_3 = PhotoImage(file=self.relative_to_assets("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(772.0, 425.5, image=self.entry_image_3)
        self.entry_3 = Text(
            bd=0,
            bg="#FFFFFF",
            font=("Inter SemiBold", 18 * -1),
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(x=618.0, y=404.0, width=308.0, height=41.0)

        self.canvas.create_text(629.0, 359.0, anchor="nw", text="Phone", fill="#000000", font=("Inter SemiBold", 20 * -1))

        self.entry_image_4 = PhotoImage(file=self.relative_to_assets("entry_4.png"))
        self.entry_bg_4 = self.canvas.create_image(909.0, 308.0, image=self.entry_image_4)
        self.entry_4 = Text(
            bd=0,
            bg="#FFFFFF",
            padx=10,
            pady=10,
            font=("Inter SemiBold", 18 * -1),
            fg="#000716",
            highlightthickness=0
        )
        self.entry_4.place(x=618.0, y=283.0, width=582.0, height=48.0)

        self.canvas.create_text(631.0, 239.0, anchor="nw", text="Address", fill="#000000", font=("Inter SemiBold", 20 * -1))

    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

window = Tk()
window.geometry("1240x600")
window.configure(bg="#FFFFFF")
app = MyApp(window)
window.mainloop()
